# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5745e90faccd6b8b8f91744a08680dec0b404bd68caa6b46d3c1e4c39bf2549795f73325c0fe8c73786172e9cc7536312cb22cab6668252ef079c2d4acfef27c

test:
  secret_key_base: 4f5e0e35f737609685ba9db07976e8f8cd3682504ff79ef882636d06e89cf87eb9e2bcdd075817db6254566a4566b281915cbab1b46658b3bb66e41b6fbe8f82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
